export enum AppPhase {
  LANDING = 'LANDING',
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  SYNTHESIS = 'SYNTHESIS',
  REVEAL = 'REVEAL',
  ERROR = 'ERROR'
}

export enum ConnectionStatus {
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  DISCONNECTED = 'DISCONNECTED',
  RECONNECTING = 'RECONNECTING'
}
